import type { TranscriptWord } from '../transcript/types';
import { analyzeTranscriptTakes, analyzeTranscriptTakesExhaustive, type TakeAnalysisInput, type TakePairDisposition } from './transcriptTakeAnalysis';

export interface TakePairLabel { left: number; right: number; disposition: TakePairDisposition; }
export interface TakeFixture extends TakeAnalysisInput { label: string; goldGroups?: ReadonlyArray<readonly number[]>; pairLabels: readonly TakePairLabel[]; options?: Parameters<typeof analyzeTranscriptTakes>[1]; }
function wordsFor(statements: readonly { text: string; gapAfter?: number; internalPauseAfter?: number }[]): TranscriptWord[] { const words: TranscriptWord[] = []; let cursor = 0; for (const statement of statements) { for (const [index, text] of statement.text.split(/\s+/u).filter(Boolean).entries()) { const start = cursor; cursor += 100; words.push({ text, start, end: cursor, speaker: 'A' }); cursor += index === statement.internalPauseAfter ? 1_200 : 40; } cursor += statement.gapAfter ?? 2_500; } return words; }
const grouped = (left: number, right: number): TakePairLabel => ({ left, right, disposition: 'GROUPED' });
const separate = (left: number, right: number): TakePairLabel => ({ left, right, disposition: 'SEPARATE' });
const possible = (left: number, right: number): TakePairLabel => ({ left, right, disposition: 'POSSIBLE_MATCH' });
export const TAKE_DETECTION_FIXTURES: readonly TakeFixture[] = [
  { label: 'explicit restart with ASR noise', sourceItemId: 'restart', transcriptGenerationId: 'v1', words: wordsFor([{ text: 'let me say that again we ship clear videos today' }, { text: 'we ship clara videos today' }]), goldGroups: [], pairLabels: [separate(0, 1)] },
  { label: 'meaningful second-take addition', sourceItemId: 'addition', transcriptGenerationId: 'v1', words: wordsFor([{ text: 'the upload workflow is' }, { text: 'the upload workflow is simple and reliable' }]), goldGroups: [], pairLabels: [possible(0, 1)] },
  { label: 'partial overlap and duplicated word', sourceItemId: 'partial', transcriptGenerationId: 'v1', words: wordsFor([{ text: 'the new plan is simple we publish friday' }, { text: 'the new plan plan is simple then notify customers' }]), goldGroups: [[0, 1]], pairLabels: [grouped(0, 1)] },
  { label: 'same topic different claim', sourceItemId: 'topic', transcriptGenerationId: 'v1', words: wordsFor([{ text: 'the editor makes video reviews easier' }, { text: 'the editor stores projects on this computer' }]), goldGroups: [], pairLabels: [separate(0, 1)] },
  { label: 'rhetorical repetition', sourceItemId: 'emphasis', transcriptGenerationId: 'v1', words: wordsFor([{ text: 'this matters for every creator', gapAfter: 700 }, { text: 'this matters for every creator' }]), goldGroups: [], pairLabels: [separate(0, 1)] },
  { label: 'internal pause is separate', sourceItemId: 'pause', transcriptGenerationId: 'v1', words: wordsFor([{ text: 'we keep the natural pause inside a single sentence', internalPauseAfter: 3 }]), goldGroups: [], pairLabels: [separate(0, 1)] },
  { label: 'distant retakes remain reviewable', sourceItemId: 'distant', transcriptGenerationId: 'v1', words: wordsFor([{ text: 'we publish helpful videos every week', gapAfter: 119_500 }, { text: 'we publish helpful videos every week' }]), goldGroups: [[0, 1]], pairLabels: [grouped(0, 1)] },
  { label: 'candidate boundary telemetry', sourceItemId: 'boundary', transcriptGenerationId: 'v1', words: wordsFor([{ text: 'we ship clear videos today' }, { text: 'we ship clear videos today' }, { text: 'we ship clear videos today' }]), goldGroups: [[0, 1]], pairLabels: [grouped(0, 1)], options: { maxPhrases: 2, maxPairCount: 1 } },
] as const;
const groupKey = (members: readonly number[]) => members.slice().sort((a, b) => a - b).join('|');
function pairRanges(analysis: ReturnType<typeof analyzeTranscriptTakes>, left: number, right: number) { return analysis.pairs.find((pair) => pair.left.first === left && pair.left.last === left && pair.right.first === right && pair.right.last === right); }
export interface TakeDetectionCorpusReport { precision: number; recall: number; falsePositives: number; falseNegatives: number; disagreements: readonly string[]; scoreDistributions: Readonly<Record<TakePairDisposition, readonly number[]>>; }
export function verifyTakeDetectionCorpus(): TakeDetectionCorpusReport { let truePositives = 0; let falsePositives = 0; let falseNegatives = 0; const disagreements: string[] = []; const scoreDistributions: Record<TakePairDisposition, number[]> = { GROUPED: [], POSSIBLE_MATCH: [], SEPARATE: [] }; for (const fixture of TAKE_DETECTION_FIXTURES) { const analysis = analyzeTranscriptTakes(fixture, fixture.options); const expectedGroups = new Set((fixture.goldGroups ?? []).map(groupKey)); const actualGroups = new Set(analysis.groups.map((group) => groupKey(group.members.map((member) => analysis.phrases.findIndex((phrase) => phrase.start === member.start))))); for (const key of actualGroups) expectedGroups.has(key) ? truePositives++ : falsePositives++; for (const key of expectedGroups) if (!actualGroups.has(key)) falseNegatives++; for (const label of fixture.pairLabels) { const pair = pairRanges(analysis, label.left, label.right); if (!pair || pair.score.disposition !== label.disposition) disagreements.push(`${fixture.label}: ${pair?.score.disposition ?? 'MISSING'} != ${label.disposition}`); else scoreDistributions[label.disposition].push(pair.score.overall); } } return { precision: truePositives / Math.max(1, truePositives + falsePositives), recall: truePositives / Math.max(1, truePositives + falseNegatives), falsePositives, falseNegatives, disagreements, scoreDistributions: Object.freeze({ GROUPED: Object.freeze(scoreDistributions.GROUPED.sort()), POSSIBLE_MATCH: Object.freeze(scoreDistributions.POSSIBLE_MATCH.sort()), SEPARATE: Object.freeze(scoreDistributions.SEPARATE.sort()) }) }; }
export function verifyOracleParity(): string[] { const failures: string[] = []; for (const fixture of TAKE_DETECTION_FIXTURES) { if (fixture.options) continue; const optimized = analyzeTranscriptTakes(fixture); const oracle = analyzeTranscriptTakesExhaustive(fixture); if (optimized.telemetry.phraseTruncated || optimized.telemetry.candidateTruncated || optimized.telemetry.pairTruncated) failures.push(`${fixture.label}: bounded enumeration truncated`); const optimizedGroups = new Set(optimized.groups.map((group) => groupKey(group.members.map((member) => optimized.phrases.findIndex((phrase) => phrase.start === member.start))))); for (const group of oracle.groups) if (!optimizedGroups.has(groupKey(group.members.map((member) => oracle.phrases.findIndex((phrase) => phrase.start === member.start))))) failures.push(`${fixture.label}: missing oracle group`); } return failures; }
