import { packTranscriptPhrases, type TranscriptPhrase } from '../transcript/phrases';
import type { TranscriptWord } from '../transcript/types';

export const TAKE_DETECTION_ALGORITHM_VERSION = 'take-detection-v2' as const;
export type TakePairDisposition = 'GROUPED' | 'POSSIBLE_MATCH' | 'SEPARATE';

export interface TakeAnalysisInput { sourceItemId: string; transcriptGenerationId: string; words: readonly TranscriptWord[]; }
export interface TakeDetectionOptions {
  maxPhrases: number; maxWordsPerCandidate: number; maxPhrasesPerCandidate: number;
  maxCandidateDistanceMs: number; maxPairCount: number; silenceThresholdMs: number;
  groupingThreshold: number; possibleMatchThreshold: number; semanticScorer?: (left: string, right: string) => number; alignmentScorer?: (left: TakeCandidate, right: TakeCandidate) => number; temporalScorer?: (left: TakeCandidate, right: TakeCandidate) => number;
}
export const DEFAULT_TAKE_DETECTION_OPTIONS: Readonly<TakeDetectionOptions> = Object.freeze({
  maxPhrases: 240, maxWordsPerCandidate: 48, maxPhrasesPerCandidate: 3, maxCandidateDistanceMs: 120_000,
  maxPairCount: 1_200, silenceThresholdMs: 500, groupingThreshold: 0.72, possibleMatchThreshold: 0.56,
});
export interface TakeScore { lexical: number; semantic: number; alignment: number; temporal: number; overall: number; disposition: TakePairDisposition; }
export interface TakeCandidate { first: number; last: number; start: number; end: number; text: string; wordCount: number; phrases: readonly TranscriptPhrase[]; wordRanges: ReadonlyArray<readonly [number, number]>; }
export interface TakePairEvaluation { left: TakeCandidate; right: TakeCandidate; score: TakeScore; }
export interface TakeMember { sourceItemId: string; start: number; end: number; wordRanges: ReadonlyArray<readonly [number, number]>; matchedWordRanges: ReadonlyArray<readonly [number, number]>; text: string; score: TakeScore; }
export interface TakeGroup { id: string; sourceItemId: string; start: number; end: number; wordRanges: ReadonlyArray<readonly [number, number]>; text: string; members: ReadonlyArray<TakeMember>; scores: ReadonlyArray<TakeScore>; }
export interface TakeDetectionTelemetry { phraseTruncated: boolean; candidateTruncated: boolean; pairTruncated: boolean; candidateCount: number; evaluatedPairCount: number; }
export type TakePhraseSnapshot = Omit<TranscriptPhrase, 'wordRanges'> & { wordRanges: ReadonlyArray<readonly [number, number]> };
export interface TakeAnalysis { sourceItemId: string; transcriptGenerationId: string; algorithmVersion: typeof TAKE_DETECTION_ALGORITHM_VERSION; phrases: ReadonlyArray<TakePhraseSnapshot>; candidates: ReadonlyArray<TakeCandidate>; pairs: ReadonlyArray<TakePairEvaluation>; groups: ReadonlyArray<TakeGroup>; telemetry: TakeDetectionTelemetry; }

const FILLERS = new Set(['uh', 'um', 'erm', 'ah', 'like']);
const SYNONYMS: Readonly<Record<string, string>> = Object.freeze({ editing: 'editor', helps: 'lets', publish: 'release', faster: 'quicker', helpful: 'useful' });
const clamp = (value: number) => Number.isFinite(value) ? Math.max(0, Math.min(1, value)) : 0;
function tokenize(text: string, semantic = false): string[] { return text.normalize('NFKC').toLocaleLowerCase().replace(/[^\p{L}\p{N}'\s]/gu, ' ').split(/\s+/u).filter((word) => word && !FILLERS.has(word)).map((word) => semantic ? SYNONYMS[word] ?? word : word); }
function overlap(left: readonly string[], right: readonly string[]): number { const a = new Set(left); const b = new Set(right); if (!a.size || !b.size) return 0; let shared = 0; for (const word of a) if (b.has(word)) shared += 1; return shared / Math.max(a.size, b.size); }
function ranges(values: readonly (readonly [number, number])[]): ReadonlyArray<readonly [number, number]> { const output: Array<readonly [number, number]> = []; for (const [start, end] of [...values].sort(([a], [b]) => a - b)) { const previous = output.at(-1); if (previous && start <= previous[1]) output[output.length - 1] = [previous[0], Math.max(previous[1], end)]; else output.push([start, end]); } return output; }
function configFor(value?: Partial<TakeDetectionOptions>): TakeDetectionOptions { const base = DEFAULT_TAKE_DETECTION_OPTIONS; const whole = (input: number | undefined, fallback: number, min: number, max: number) => Math.max(min, Math.min(max, Math.floor(Number.isFinite(input) ? input! : fallback))); const decimal = (input: number | undefined, fallback: number) => Math.max(0, Math.min(1, Number.isFinite(input) ? input! : fallback)); return { maxPhrases: whole(value?.maxPhrases, base.maxPhrases, 1, 2_000), maxWordsPerCandidate: whole(value?.maxWordsPerCandidate, base.maxWordsPerCandidate, 1, 300), maxPhrasesPerCandidate: whole(value?.maxPhrasesPerCandidate, base.maxPhrasesPerCandidate, 1, 8), maxCandidateDistanceMs: whole(value?.maxCandidateDistanceMs, base.maxCandidateDistanceMs, 0, 3_600_000), maxPairCount: whole(value?.maxPairCount, base.maxPairCount, 1, 10_000), silenceThresholdMs: whole(value?.silenceThresholdMs, base.silenceThresholdMs, 0, 10_000), groupingThreshold: decimal(value?.groupingThreshold, base.groupingThreshold), possibleMatchThreshold: decimal(value?.possibleMatchThreshold, base.possibleMatchThreshold), semanticScorer: value?.semanticScorer, alignmentScorer: value?.alignmentScorer, temporalScorer: value?.temporalScorer }; }
function candidatesFor(phrases: readonly TranscriptPhrase[], options: TakeDetectionOptions, bounded: boolean): TakeCandidate[] { const output: TakeCandidate[] = []; for (let first = 0; first < phrases.length; first += 1) { let count = 0; for (let last = first; last < phrases.length && (!bounded || last < first + options.maxPhrasesPerCandidate); last += 1) { count += phrases[last]!.wordCount; if (bounded && count > options.maxWordsPerCandidate) break; const window = phrases.slice(first, last + 1); output.push(Object.freeze({ first, last, wordCount: count, phrases: window, start: window[0]!.start, end: window.at(-1)!.end, text: window.map((phrase) => phrase.text).join(' '), wordRanges: ranges(window.flatMap((phrase) => phrase.wordRanges)) })); } } return output; }
function localAlignment(left: TakeCandidate, right: TakeCandidate, options: TakeDetectionOptions): number { const matrix = Array.from({ length: left.phrases.length + 1 }, () => Array<number>(right.phrases.length + 1).fill(0)); let best = 0; for (let row = 1; row < matrix.length; row += 1) for (let column = 1; column < matrix[0]!.length; column += 1) { const a = left.phrases[row - 1]!.text; const b = right.phrases[column - 1]!.text; const similarity = overlap(tokenize(a), tokenize(b)) * 0.55 + (options.semanticScorer ? clamp(options.semanticScorer(a, b)) : overlap(tokenize(a, true), tokenize(b, true))) * 0.45; matrix[row]![column] = similarity >= 0.4 ? matrix[row - 1]![column - 1]! + similarity : 0; best = Math.max(best, matrix[row]![column]!); } return clamp(best / Math.max(1, Math.min(left.phrases.length, right.phrases.length))); }
/** Canonical scoring path used by bounded detection and the exhaustive oracle. */
export function evaluateTakePair(left: TakeCandidate, right: TakeCandidate, supplied?: Partial<TakeDetectionOptions>): TakePairEvaluation { const options = configFor(supplied); const lexical = overlap(tokenize(left.text), tokenize(right.text)); const semantic = options.semanticScorer ? clamp(options.semanticScorer(left.text, right.text)) : overlap(tokenize(left.text, true), tokenize(right.text, true)); const alignment = options.alignmentScorer ? clamp(options.alignmentScorer(left, right)) : localAlignment(left, right, options); const temporal = options.temporalScorer ? clamp(options.temporalScorer(left, right)) : clamp(1 - Math.max(0, right.start - left.end) / Math.max(1, options.maxCandidateDistanceMs)); const restart = left.wordCount < right.wordCount && lexical >= 0.5 ? 0.06 : 0; const emphasis = lexical === 1 && right.start - left.end < 1_500 && left.wordCount === right.wordCount ? 0.45 : 1; const overall = alignment && (lexical >= 0.3 || semantic >= 0.5) ? clamp((lexical * .35 + semantic * .2 + alignment * .3 + temporal * .15 + restart) * emphasis) : 0; const disposition: TakePairDisposition = overall >= options.groupingThreshold ? 'GROUPED' : overall >= options.possibleMatchThreshold ? 'POSSIBLE_MATCH' : 'SEPARATE'; return Object.freeze({ left, right, score: Object.freeze({ lexical, semantic, alignment, temporal, overall, disposition }) }); }
const key = (candidate: TakeCandidate) => `${candidate.first}:${candidate.last}`;
function hash(input: string): string { let value = 2_166_136_261; for (let index = 0; index < input.length; index += 1) value = Math.imul(value ^ input.charCodeAt(index), 16_777_619); return (value >>> 0).toString(36); }
function matchedRange(candidate: TakeCandidate, other: TakeCandidate): ReadonlyArray<readonly [number, number]> { const own = tokenize(candidate.text); const matching = own.map((word, index) => new Set(tokenize(other.text)).has(word) ? index : -1).filter((index) => index >= 0); if (matching.length < 3) return candidate.wordRanges; const start = candidate.wordRanges[0]?.[0] ?? 0; const end = candidate.wordRanges.at(-1)?.[1] ?? start; return [[start + Math.floor(matching[0]! / own.length * (end - start)), start + Math.ceil((matching.at(-1)! + 1) / own.length * (end - start))]]; }
function groupsFor(sourceItemId: string, generation: string, pairs: readonly TakePairEvaluation[]): TakeGroup[] { const entries = new Map<string, TakeCandidate>(); const edges = new Map<string, Set<string>>(); const scores = new Map<string, TakeScore>(); for (const pair of pairs.filter((pair) => pair.score.disposition === 'GROUPED')) { const left = key(pair.left); const right = key(pair.right); entries.set(left, pair.left); entries.set(right, pair.right); for (const [from, to] of [[left, right], [right, left]] as const) (edges.get(from) ?? edges.set(from, new Set()).get(from)!).add(to); for (const item of [left, right]) if ((scores.get(item)?.overall ?? -1) < pair.score.overall) scores.set(item, pair.score); } const seen = new Set<string>(); const output: TakeGroup[] = []; for (const seed of [...entries.keys()].sort()) { if (seen.has(seed)) continue; const queue = [seed]; const component: string[] = []; seen.add(seed); while (queue.length) { const item = queue.shift()!; component.push(item); for (const neighbor of edges.get(item) ?? []) if (!seen.has(neighbor)) { seen.add(neighbor); queue.push(neighbor); } } const all = component.map((item) => entries.get(item)!).sort((a, b) => a.start - b.start || a.first - b.first); const singles = all.filter((candidate) => candidate.first === candidate.last); const unique = singles.length >= 2 ? singles : all.filter((candidate, index) => !all.slice(0, index).some((prior) => prior.first <= candidate.first && prior.last >= candidate.last)); if (unique.length < 2) continue; const members = unique.map((candidate) => Object.freeze({ sourceItemId, start: candidate.start, end: candidate.end, wordRanges: candidate.wordRanges, matchedWordRanges: matchedRange(candidate, unique.find((other) => other !== candidate)!), text: candidate.text, score: scores.get(key(candidate))! })); const identity = [TAKE_DETECTION_ALGORITHM_VERSION, generation, ...members.flatMap((member) => member.wordRanges.map(([start, end]) => `${start}:${end}`))].join('|'); output.push(Object.freeze({ id: `take-${hash(identity)}`, sourceItemId, start: members[0]!.start, end: members.at(-1)!.end, wordRanges: ranges(members.flatMap((member) => member.wordRanges)), text: members.map((member) => member.text).join(' / '), members: Object.freeze(members), scores: Object.freeze([...new Set(members.map((member) => member.score))]) })); } return output.sort((a, b) => a.start - b.start || a.id.localeCompare(b.id)); }
function analyze(input: TakeAnalysisInput, supplied: Partial<TakeDetectionOptions> | undefined, bounded: boolean): TakeAnalysis { const options = configFor(supplied); const packed = input.sourceItemId.trim() && input.transcriptGenerationId.trim() ? packTranscriptPhrases(input.words, { sourceItemId: input.sourceItemId, silenceThresholdMs: options.silenceThresholdMs, maxWordsPerPhrase: bounded ? options.maxWordsPerCandidate : Number.MAX_SAFE_INTEGER }) : []; const phrases = bounded ? packed.slice(0, options.maxPhrases) : packed; const candidates = candidatesFor(phrases, options, bounded); const pairs: TakePairEvaluation[] = []; let eligible = 0; // simplification: bounded O(candidate²) enumeration; move this scan to a worker before increasing limits.
  outer: for (let leftIndex = 0; leftIndex < candidates.length; leftIndex += 1) for (let rightIndex = leftIndex + 1; rightIndex < candidates.length; rightIndex += 1) { const left = candidates[leftIndex]!; const right = candidates[rightIndex]!; if (left.last >= right.first || right.start - left.end > options.maxCandidateDistanceMs) continue; eligible += 1; if (bounded && pairs.length >= options.maxPairCount) break outer; pairs.push(evaluateTakePair(left, right, options)); }
  const telemetry = Object.freeze({ phraseTruncated: bounded && packed.length > phrases.length, candidateTruncated: bounded && candidatesFor(phrases, options, false).length > candidates.length, pairTruncated: bounded && eligible > pairs.length, candidateCount: candidates.length, evaluatedPairCount: pairs.length }); return Object.freeze({ sourceItemId: input.sourceItemId, transcriptGenerationId: input.transcriptGenerationId, algorithmVersion: TAKE_DETECTION_ALGORITHM_VERSION, phrases: Object.freeze(phrases.map((phrase) => Object.freeze({ ...phrase, wordRanges: Object.freeze(phrase.wordRanges.map(([start, end]) => [start, end] as const)) }))), candidates: Object.freeze(candidates), pairs: Object.freeze(pairs), groups: Object.freeze(groupsFor(input.sourceItemId, input.transcriptGenerationId, pairs)), telemetry }); }
export function analyzeTranscriptTakes(input: TakeAnalysisInput, supplied?: Partial<TakeDetectionOptions>): TakeAnalysis { return analyze(input, supplied, true); }
export function analyzeTranscriptTakesExhaustive(input: TakeAnalysisInput, supplied?: Partial<TakeDetectionOptions>): TakeAnalysis { return analyze(input, supplied, false); }
export function isTakeAnalysisCurrent(analysis: TakeAnalysis | null | undefined, transcriptGenerationId: string): boolean { return !!analysis && analysis.algorithmVersion === TAKE_DETECTION_ALGORITHM_VERSION && !!transcriptGenerationId.trim() && analysis.transcriptGenerationId === transcriptGenerationId; }
